# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created: Mon Aug  3 03:30:25 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frm_login(object):
    def setupUi(self, frm_login):
        frm_login.setObjectName("frm_login")
        frm_login.setWindowModality(QtCore.Qt.NonModal)
        frm_login.resize(321, 472)
        frm_login.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pwytter.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frm_login.setWindowIcon(icon)
        self.frame_login = QtGui.QFrame(frm_login)
        self.frame_login.setGeometry(QtCore.QRect(30, 30, 261, 401))
        self.frame_login.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.lEditUserName = QtGui.QLineEdit(self.frame_login)
        self.lEditUserName.setGeometry(QtCore.QRect(130, 120, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEditUserName.setFont(font)
        self.lEditUserName.setMaxLength(40)
        self.lEditUserName.setObjectName("lEditUserName")
        self.lEditPassword = QtGui.QLineEdit(self.frame_login)
        self.lEditPassword.setGeometry(QtCore.QRect(130, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEditPassword.setFont(font)
        self.lEditPassword.setMaxLength(20)
        self.lEditPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lEditPassword.setObjectName("lEditPassword")
        self.buttonSignIn = QtGui.QPushButton(self.frame_login)
        self.buttonSignIn.setGeometry(QtCore.QRect(20, 340, 80, 28))
        self.buttonSignIn.setFlat(False)
        self.buttonSignIn.setObjectName("buttonSignIn")
        self.buttonCancel = QtGui.QPushButton(self.frame_login)
        self.buttonCancel.setGeometry(QtCore.QRect(130, 340, 80, 28))
        self.buttonCancel.setObjectName("buttonCancel")
        self.chkRememberMe = QtGui.QCheckBox(self.frame_login)
        self.chkRememberMe.setGeometry(QtCore.QRect(20, 300, 201, 24))
        self.chkRememberMe.setObjectName("chkRememberMe")
        self.lblUserName = QtGui.QLabel(self.frame_login)
        self.lblUserName.setGeometry(QtCore.QRect(20, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.lblUserName.setFont(font)
        self.lblUserName.setWordWrap(False)
        self.lblUserName.setObjectName("lblUserName")
        self.lblPassword = QtGui.QLabel(self.frame_login)
        self.lblPassword.setGeometry(QtCore.QRect(20, 170, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName("lblPassword")
        self.lblPwytterIco = QtGui.QLabel(self.frame_login)
        self.lblPwytterIco.setGeometry(QtCore.QRect(100, 10, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.lblPwytterIco.setFont(font)
        self.lblPwytterIco.setFrameShadow(QtGui.QFrame.Raised)
        self.lblPwytterIco.setPixmap(QtGui.QPixmap(":/pwytter"))
        self.lblPwytterIco.setObjectName("lblPwytterIco")
        self.dSignIn = QtGui.QDial(self.frame_login)
        self.dSignIn.setGeometry(QtCore.QRect(110, 210, 50, 64))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dSignIn.setFont(font)
        self.dSignIn.setAutoFillBackground(False)
        self.dSignIn.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.dSignIn.setNotchesVisible(True)
        self.dSignIn.setObjectName("dSignIn")
        self.line = QtGui.QFrame(self.frame_login)
        self.line.setGeometry(QtCore.QRect(70, 90, 118, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(frm_login)
        QtCore.QMetaObject.connectSlotsByName(frm_login)

    def retranslateUi(self, frm_login):
        frm_login.setWindowTitle(QtGui.QApplication.translate("frm_login", "Log In- Pwytter", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSignIn.setText(QtGui.QApplication.translate("frm_login", "Sign In", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCancel.setText(QtGui.QApplication.translate("frm_login", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRememberMe.setText(QtGui.QApplication.translate("frm_login", "Remember me on this computer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUserName.setText(QtGui.QApplication.translate("frm_login", "UserName", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("frm_login", "Password", None, QtGui.QApplication.UnicodeUTF8))

import ImIcon_rc
