# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesdialog.ui'
#
# Created: Sun Jul 19 12:40:50 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(522, 660)
        self.verticalLayout_9 = QtGui.QVBoxLayout(PreferencesDialog)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtGui.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.SynchronizationIntervalSpinBox = QtGui.QSpinBox(self.tab)
        self.SynchronizationIntervalSpinBox.setMinimum(120)
        self.SynchronizationIntervalSpinBox.setMaximum(604800)
        self.SynchronizationIntervalSpinBox.setSingleStep(30)
        self.SynchronizationIntervalSpinBox.setProperty("value", QtCore.QVariant(180))
        self.SynchronizationIntervalSpinBox.setObjectName("SynchronizationIntervalSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.SynchronizationIntervalSpinBox)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.TweetsPerPageSpinBox = QtGui.QSpinBox(self.tab)
        self.TweetsPerPageSpinBox.setMinimum(1)
        self.TweetsPerPageSpinBox.setMaximum(100)
        self.TweetsPerPageSpinBox.setSingleStep(5)
        self.TweetsPerPageSpinBox.setProperty("value", QtCore.QVariant(10))
        self.TweetsPerPageSpinBox.setObjectName("TweetsPerPageSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.TweetsPerPageSpinBox)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.UsersPerPageSpinBox = QtGui.QSpinBox(self.tab)
        self.UsersPerPageSpinBox.setMinimum(1)
        self.UsersPerPageSpinBox.setMaximum(100)
        self.UsersPerPageSpinBox.setSingleStep(5)
        self.UsersPerPageSpinBox.setProperty("value", QtCore.QVariant(15))
        self.UsersPerPageSpinBox.setObjectName("UsersPerPageSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.UsersPerPageSpinBox)
        self.ShowMainWindowOnStartupCheckBox = QtGui.QCheckBox(self.tab)
        self.ShowMainWindowOnStartupCheckBox.setChecked(True)
        self.ShowMainWindowOnStartupCheckBox.setObjectName("ShowMainWindowOnStartupCheckBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.ShowMainWindowOnStartupCheckBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.NotifyOnNewTweetCheckBox = QtGui.QCheckBox(self.tab_2)
        self.NotifyOnNewTweetCheckBox.setObjectName("NotifyOnNewTweetCheckBox")
        self.verticalLayout_6.addWidget(self.NotifyOnNewTweetCheckBox)
        self.NotifyOnNewReplyCheckBox = QtGui.QCheckBox(self.tab_2)
        self.NotifyOnNewReplyCheckBox.setObjectName("NotifyOnNewReplyCheckBox")
        self.verticalLayout_6.addWidget(self.NotifyOnNewReplyCheckBox)
        self.NotifyOnNewDirectMessageCheckBox = QtGui.QCheckBox(self.tab_2)
        self.NotifyOnNewDirectMessageCheckBox.setObjectName("NotifyOnNewDirectMessageCheckBox")
        self.verticalLayout_6.addWidget(self.NotifyOnNewDirectMessageCheckBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.NotifyOnNewFollowerCheckBox = QtGui.QCheckBox(self.tab_2)
        self.NotifyOnNewFollowerCheckBox.setObjectName("NotifyOnNewFollowerCheckBox")
        self.verticalLayout_7.addWidget(self.NotifyOnNewFollowerCheckBox)
        self.NotifyOnNewFriendCheckBox = QtGui.QCheckBox(self.tab_2)
        self.NotifyOnNewFriendCheckBox.setObjectName("NotifyOnNewFriendCheckBox")
        self.verticalLayout_7.addWidget(self.NotifyOnNewFriendCheckBox)
        self.NotifyOnSyncCompletedCheckBox = QtGui.QCheckBox(self.tab_2)
        self.NotifyOnSyncCompletedCheckBox.setObjectName("NotifyOnSyncCompletedCheckBox")
        self.verticalLayout_7.addWidget(self.NotifyOnSyncCompletedCheckBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.WhitelistedUserListWidget = QtGui.QListWidget(self.groupBox_3)
        self.WhitelistedUserListWidget.setObjectName("WhitelistedUserListWidget")
        self.verticalLayout_2.addWidget(self.WhitelistedUserListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.BlackListUserToolButton = QtGui.QToolButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/tango/22x22/actions/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackListUserToolButton.setIcon(icon)
        self.BlackListUserToolButton.setObjectName("BlackListUserToolButton")
        self.verticalLayout_3.addWidget(self.BlackListUserToolButton)
        self.WhiteListUserToolButton = QtGui.QToolButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/tango/22x22/actions/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteListUserToolButton.setIcon(icon1)
        self.WhiteListUserToolButton.setObjectName("WhiteListUserToolButton")
        self.verticalLayout_3.addWidget(self.WhiteListUserToolButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.BlacklistUserListWidget = QtGui.QListWidget(self.groupBox_3)
        self.BlacklistUserListWidget.setObjectName("BlacklistUserListWidget")
        self.verticalLayout.addWidget(self.BlacklistUserListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BlacklistTagListWidget = QtGui.QListWidget(self.groupBox)
        self.BlacklistTagListWidget.setObjectName("BlacklistTagListWidget")
        self.verticalLayout_4.addWidget(self.BlacklistTagListWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BlacklistTagLineEdit = QtGui.QLineEdit(self.groupBox)
        self.BlacklistTagLineEdit.setObjectName("BlacklistTagLineEdit")
        self.horizontalLayout_4.addWidget(self.BlacklistTagLineEdit)
        self.AddBlackListTagButton = QtGui.QPushButton(self.groupBox)
        self.AddBlackListTagButton.setObjectName("AddBlackListTagButton")
        self.horizontalLayout_4.addWidget(self.AddBlackListTagButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.WhitelistTagListWidget = QtGui.QListWidget(self.groupBox_2)
        self.WhitelistTagListWidget.setObjectName("WhitelistTagListWidget")
        self.verticalLayout_5.addWidget(self.WhitelistTagListWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.WhitelistTagLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.WhitelistTagLineEdit.setObjectName("WhitelistTagLineEdit")
        self.horizontalLayout_3.addWidget(self.WhitelistTagLineEdit)
        self.AddWhiteListTagButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddWhiteListTagButton.sizePolicy().hasHeightForWidth())
        self.AddWhiteListTagButton.setSizePolicy(sizePolicy)
        self.AddWhiteListTagButton.setObjectName("AddWhiteListTagButton")
        self.horizontalLayout_3.addWidget(self.AddWhiteListTagButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.textBrowser = QtGui.QTextBrowser(self.groupBox_4)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_10.addWidget(self.textBrowser)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.listWidget_5 = QtGui.QListWidget(self.tab_3)
        self.listWidget_5.setObjectName("listWidget_5")
        self.verticalLayout_11.addWidget(self.listWidget_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_9.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtGui.QApplication.translate("PreferencesDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PreferencesDialog", "Synchronization interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.SynchronizationIntervalSpinBox.setSuffix(QtGui.QApplication.translate("PreferencesDialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PreferencesDialog", "Number of tweet per page:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PreferencesDialog", "Number of users per page:", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowMainWindowOnStartupCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Show main window at startup.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PreferencesDialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.NotifyOnNewTweetCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Notification on new tweet in timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.NotifyOnNewReplyCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Notification on new reply", None, QtGui.QApplication.UnicodeUTF8))
        self.NotifyOnNewDirectMessageCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Notification on new direct message", None, QtGui.QApplication.UnicodeUTF8))
        self.NotifyOnNewFollowerCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Notification on new follower", None, QtGui.QApplication.UnicodeUTF8))
        self.NotifyOnNewFriendCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Notification on new friend", None, QtGui.QApplication.UnicodeUTF8))
        self.NotifyOnSyncCompletedCheckBox.setText(QtGui.QApplication.translate("PreferencesDialog", "Notification on synchronization completed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PreferencesDialog", "Blacklist users", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferencesDialog", "Whitelisted users", None, QtGui.QApplication.UnicodeUTF8))
        self.BlackListUserToolButton.setText(QtGui.QApplication.translate("PreferencesDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.WhiteListUserToolButton.setText(QtGui.QApplication.translate("PreferencesDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreferencesDialog", "Blacklisted users", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PreferencesDialog", "Blacklisted tags", None, QtGui.QApplication.UnicodeUTF8))
        self.AddBlackListTagButton.setText(QtGui.QApplication.translate("PreferencesDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PreferencesDialog", "Whitelisted tags", None, QtGui.QApplication.UnicodeUTF8))
        self.AddWhiteListTagButton.setText(QtGui.QApplication.translate("PreferencesDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PreferencesDialog", "Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PreferencesDialog", "Theme information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PreferencesDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PreferencesDialog", "Select theme", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("PreferencesDialog", "Theme", None, QtGui.QApplication.UnicodeUTF8))

import ressources_rc
